FROM node:alpine

WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY ./package.json ./

RUN npm install

COPY . ./

EXPOSE 3000

CMD ["npm", "run", "start"]