version: '3'

services:
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app 
    
    home:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./home
        volumes:
            - /app/node_modules
            - ./home:/app    
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - "3001:3001"          
    client:
        depends_on:
            - home
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./shell
        volumes:
            - /app/node_modules
            - ./shell:/app    
        environment:
            - CHOKIDAR_USEPOLLING=true 
        ports:
            - "3000:3000"                 
    # nginx-proxy:
    #     depends_on:
    #         - api
    #         - client
    #     restart: always
    #     build:
    #         dockerfile: Dockerfile.dev
    #         context: ./nginx
    #     ports:
    #         - '4050:80'                            