# Use an official Node.js runtime as a base image
FROM node:16-alpine AS build

# Set the working directory
WORKDIR /src

# Copy the package.json and install dependencies
COPY package.json package-lock.json* ./
RUN npm ci --silent

# Copy the source code
COPY . .

# Build the application
RUN npm run build

# Use a lightweight Nginx image for serving the built React application
FROM nginx:alpine

# Copy the built application from the build stage to the Nginx server
COPY --from=build /app/build /usr/share/nginx/html

# Copy the Nginx configuration file if needed
# COPY nginx.conf /etc/nginx/nginx.conf

# Expose the default Nginx port
EXPOSE 80
