# Use an official Node.js runtime as a base image
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy the package.json and install dependencies
COPY package.json package-lock.json* ./
RUN npm ci --silent

# Copy the source code
COPY . .

# Expose the port the server is running on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
